{"name":"Dataflow 1","ppdf:dataflowId":"a93ea08c-6f9f-43fd-b71c-f0db52863caa","ppdf:owner":{"tenantId":"b30f4b44-46c6-4070-9997-f87b38d4771c","userId":"2c26a2e5-2656-4375-a2fd-ea4c498e2f92"},"ppdf:fastCopy":true,"version":"1.0","culture":"en-US","modifiedTime":"2025-11-07T13:38:13.7111606+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"main":{"queryId":"d66a5adf-ae86-438b-a756-b21bac5575fc","queryName":"main","loadEnabled":true},"avg_rating_bookid":{"queryId":"f97c44e8-77e6-4968-acec-fb93074a8121","queryName":"avg_rating_bookid","loadEnabled":true},"review_count":{"queryId":"b897b02e-b67e-490d-8987-7e2ca0ff2e53","queryName":"review_count","loadEnabled":true},"avg_rating_authorname":{"queryId":"ed4e7727-bdac-4cfd-8771-b38243279da8","queryName":"avg_rating_authorname","loadEnabled":true},"word_count_reviews":{"queryId":"0f79362b-cdcc-4000-ad09-5f9f3a3690bb","queryName":"word_count_reviews","loadEnabled":true}},"document":"section Section1;\r\nshared main = let\n  Source = AzureStorage.DataLake(\n  \"https://goodreadsreviews60107070.dfs.core.windows.net/lakehouse/gold/curated_reviews/\",\n  [HierarchicalNavigation=true]\n  ),\n  DeltaTable = DeltaLake.Table(Source),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(DeltaTable, {{\"review_id\", type text}, {\"book_id\", type text}, {\"title\", type text}, {\"author_id\", type text}, {\"name\", type text}, {\"user_id\", type text}, {\"rating\", Int64.Type}, {\"review_text\", type text}, {\"language_code\", type text}, {\"n_votes\", Int64.Type}}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Changed column type\", \"date_added_iso\", each let\r\n    txt    = [date_added],\r\n    parts  = Text.Split(Text.Trim(txt), \" \"),          // [\"Fri\",\"Jul\",\"27\",\"14:06:28\",\"-0700\",\"2012\"]\r\n    monAbbr= try parts{1} otherwise null,\r\n    dayTxt = try parts{2} otherwise null,\r\n    yearTxt= try parts{5} otherwise null,\r\n\r\n    monNum = try Record.Field(\r\n                [Jan=1,Feb=2,Mar=3,Apr=4,May=5,Jun=6,Jul=7,Aug=8,Sep=9,Oct=10,Nov=11,Dec=12],\r\n                monAbbr) otherwise null,\r\n\r\n    iso = if monNum <> null and dayTxt <> null and yearTxt <> null then\r\n            Text.From(Number.FromText(yearTxt)) & \"-\" &\r\n            Text.PadStart(Text.From(monNum), 2, \"0\") & \"-\" &\r\n            Text.PadStart(Text.From(Number.FromText(dayTxt)), 2, \"0\")\r\n          else null\r\nin\r\n    iso), {{\"date_added_iso\", type date}}),\r\n  #\"Removed blank rows\" = Table.SelectRows(#\"Added custom\", each [rating] <> null),\r\n  #\"Removed blank rows 1\" = Table.SelectRows(#\"Removed blank rows\", each [book_id] <> null and [book_id] <> \"\"),\r\n  #\"Removed blank rows 2\" = Table.SelectRows(#\"Removed blank rows 1\",  each [review_text] <> null and [review_text] <> \"\"),\r\n  #\"Added custom 1\" = Table.TransformColumnTypes(Table.AddColumn(#\"Removed blank rows 2\", \"review_length\", each Text.Length(Text.Trim([review_text]))), {{\"review_length\", Int64.Type}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Added custom 1\", each [review_length] >= 10),\r\n  #\"Removed errors\" = Table.RemoveRowsWithErrors(#\"Filtered rows\", {\"date_added_iso\"}),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Removed errors\", each [date_added_iso] < #date(2025, 11, 7)),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Filtered rows 1\", null, 0, Replacer.ReplaceValue, {\"n_votes\"}),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Replaced value\", \"\", \"Unknown\", Replacer.ReplaceValue, {\"language_code\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Replaced value 1\", {{\"title\", each Text.Trim(_), type nullable text}}),\r\n  #\"Trimmed text 1\" = Table.TransformColumns(#\"Trimmed text\", {{\"name\", each Text.Trim(_), type nullable text}}),\r\n  #\"Trimmed text 2\" = Table.TransformColumns(#\"Trimmed text 1\", {{\"review_text\", each Text.Trim(_), type nullable text}}),\r\n  #\"Capitalized each word\" = Table.TransformColumns(#\"Trimmed text 2\", {{\"title\", each Text.Proper(_), type nullable text}}),\r\n  #\"Capitalized each word 1\" = Table.TransformColumns(#\"Capitalized each word\", {{\"name\", each Text.Proper(_), type nullable text}}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Capitalized each word 1\", {\"book_id\"}, avg_rating_bookid, {\"book_id\"}, \"Query (3)\", JoinKind.LeftOuter),\r\n  #\"From Value\" = Table.FromValue(#\"Merged queries\"),\r\n  #\"Remove Columns\" = Table.RemoveColumns(#\"From Value\", Table.ColumnsOfType(#\"From Value\", {type table, type record, type list, type nullable binary, type binary, type function}))\r\n\r\n\r\n\nin\n  #\"Remove Columns\";\r\nshared avg_rating_bookid = let\n  Source = AzureStorage.DataLake(\n  \"https://goodreadsreviews60107070.dfs.core.windows.net/lakehouse/gold/curated_reviews/\",\n  [HierarchicalNavigation=true]\n  ),\n  DeltaTable = DeltaLake.Table(Source),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(DeltaTable, {{\"review_id\", type text}, {\"book_id\", type text}, {\"title\", type text}, {\"author_id\", type text}, {\"name\", type text}, {\"user_id\", type text}, {\"rating\", Int64.Type}, {\"review_text\", type text}, {\"language_code\", type text}, {\"n_votes\", Int64.Type}}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Changed column type\", \"date_added_iso\", each let\r\n    txt    = [date_added],\r\n    parts  = Text.Split(Text.Trim(txt), \" \"),          // [\"Fri\",\"Jul\",\"27\",\"14:06:28\",\"-0700\",\"2012\"]\r\n    monAbbr= try parts{1} otherwise null,\r\n    dayTxt = try parts{2} otherwise null,\r\n    yearTxt= try parts{5} otherwise null,\r\n\r\n    monNum = try Record.Field(\r\n                [Jan=1,Feb=2,Mar=3,Apr=4,May=5,Jun=6,Jul=7,Aug=8,Sep=9,Oct=10,Nov=11,Dec=12],\r\n                monAbbr) otherwise null,\r\n\r\n    iso = if monNum <> null and dayTxt <> null and yearTxt <> null then\r\n            Text.From(Number.FromText(yearTxt)) & \"-\" &\r\n            Text.PadStart(Text.From(monNum), 2, \"0\") & \"-\" &\r\n            Text.PadStart(Text.From(Number.FromText(dayTxt)), 2, \"0\")\r\n          else null\r\nin\r\n    iso), {{\"date_added_iso\", type date}}),\r\n  #\"Removed blank rows\" = Table.SelectRows(#\"Added custom\", each [rating] <> null),\r\n  #\"Removed blank rows 1\" = Table.SelectRows(#\"Removed blank rows\", each [book_id] <> null and [book_id] <> \"\"),\r\n  #\"Removed blank rows 2\" = Table.SelectRows(#\"Removed blank rows 1\",  each [review_text] <> null and [review_text] <> \"\"),\r\n  #\"Added custom 1\" = Table.TransformColumnTypes(Table.AddColumn(#\"Removed blank rows 2\", \"review_length\", each Text.Length(Text.Trim([review_text]))), {{\"review_length\", Int64.Type}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Added custom 1\", each [review_length] >= 10),\r\n  #\"Removed errors\" = Table.RemoveRowsWithErrors(#\"Filtered rows\", {\"date_added_iso\"}),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Removed errors\", each [date_added_iso] < #date(2025, 11, 7)),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Filtered rows 1\", null, 0, Replacer.ReplaceValue, {\"n_votes\"}),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Replaced value\", \"\", \"Unknown\", Replacer.ReplaceValue, {\"language_code\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Replaced value 1\", {{\"title\", each Text.Trim(_), type nullable text}}),\r\n  #\"Trimmed text 1\" = Table.TransformColumns(#\"Trimmed text\", {{\"name\", each Text.Trim(_), type nullable text}}),\r\n  #\"Trimmed text 2\" = Table.TransformColumns(#\"Trimmed text 1\", {{\"review_text\", each Text.Trim(_), type nullable text}}),\r\n  #\"Capitalized each word\" = Table.TransformColumns(#\"Trimmed text 2\", {{\"title\", each Text.Proper(_), type nullable text}}),\r\n  #\"Capitalized each word 1\" = Table.TransformColumns(#\"Capitalized each word\", {{\"name\", each Text.Proper(_), type nullable text}}),\r\n  #\"Grouped rows\" = Table.Group(#\"Capitalized each word 1\", {\"book_id\"}, {{\"avg_rating\", each List.Average([rating]), type nullable number}})\r\n\r\n\r\n\nin\n  #\"Grouped rows\";\r\nshared review_count = let\n  Source = AzureStorage.DataLake(\n  \"https://goodreadsreviews60107070.dfs.core.windows.net/lakehouse/gold/curated_reviews/\",\n  [HierarchicalNavigation=true]\n  ),\n  DeltaTable = DeltaLake.Table(Source),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(DeltaTable, {{\"review_id\", type text}, {\"book_id\", type text}, {\"title\", type text}, {\"author_id\", type text}, {\"name\", type text}, {\"user_id\", type text}, {\"rating\", Int64.Type}, {\"review_text\", type text}, {\"language_code\", type text}, {\"n_votes\", Int64.Type}}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Changed column type\", \"date_added_iso\", each let\r\n    txt    = [date_added],\r\n    parts  = Text.Split(Text.Trim(txt), \" \"),          // [\"Fri\",\"Jul\",\"27\",\"14:06:28\",\"-0700\",\"2012\"]\r\n    monAbbr= try parts{1} otherwise null,\r\n    dayTxt = try parts{2} otherwise null,\r\n    yearTxt= try parts{5} otherwise null,\r\n\r\n    monNum = try Record.Field(\r\n                [Jan=1,Feb=2,Mar=3,Apr=4,May=5,Jun=6,Jul=7,Aug=8,Sep=9,Oct=10,Nov=11,Dec=12],\r\n                monAbbr) otherwise null,\r\n\r\n    iso = if monNum <> null and dayTxt <> null and yearTxt <> null then\r\n            Text.From(Number.FromText(yearTxt)) & \"-\" &\r\n            Text.PadStart(Text.From(monNum), 2, \"0\") & \"-\" &\r\n            Text.PadStart(Text.From(Number.FromText(dayTxt)), 2, \"0\")\r\n          else null\r\nin\r\n    iso), {{\"date_added_iso\", type date}}),\r\n  #\"Removed blank rows\" = Table.SelectRows(#\"Added custom\", each [rating] <> null),\r\n  #\"Removed blank rows 1\" = Table.SelectRows(#\"Removed blank rows\", each [book_id] <> null and [book_id] <> \"\"),\r\n  #\"Removed blank rows 2\" = Table.SelectRows(#\"Removed blank rows 1\",  each [review_text] <> null and [review_text] <> \"\"),\r\n  #\"Added custom 1\" = Table.TransformColumnTypes(Table.AddColumn(#\"Removed blank rows 2\", \"review_length\", each Text.Length(Text.Trim([review_text]))), {{\"review_length\", Int64.Type}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Added custom 1\", each [review_length] >= 10),\r\n  #\"Removed errors\" = Table.RemoveRowsWithErrors(#\"Filtered rows\", {\"date_added_iso\"}),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Removed errors\", each [date_added_iso] < #date(2025, 11, 7)),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Filtered rows 1\", null, 0, Replacer.ReplaceValue, {\"n_votes\"}),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Replaced value\", \"\", \"Unknown\", Replacer.ReplaceValue, {\"language_code\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Replaced value 1\", {{\"title\", each Text.Trim(_), type nullable text}}),\r\n  #\"Trimmed text 1\" = Table.TransformColumns(#\"Trimmed text\", {{\"name\", each Text.Trim(_), type nullable text}}),\r\n  #\"Trimmed text 2\" = Table.TransformColumns(#\"Trimmed text 1\", {{\"review_text\", each Text.Trim(_), type nullable text}}),\r\n  #\"Capitalized each word\" = Table.TransformColumns(#\"Trimmed text 2\", {{\"title\", each Text.Proper(_), type nullable text}}),\r\n  #\"Capitalized each word 1\" = Table.TransformColumns(#\"Capitalized each word\", {{\"name\", each Text.Proper(_), type nullable text}}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Capitalized each word 1\", {\"book_id\"}, avg_rating_bookid, {\"book_id\"}, \"Query (3)\", JoinKind.LeftOuter),\r\n  #\"Grouped rows\" = Table.Group(#\"Merged queries\", {\"book_id\"}, {{\"review_count\", each Table.RowCount(_), Int64.Type}})\r\n\r\n\r\n\nin\n  #\"Grouped rows\";\r\nshared avg_rating_authorname = let\n  Source = AzureStorage.DataLake(\n  \"https://goodreadsreviews60107070.dfs.core.windows.net/lakehouse/gold/curated_reviews/\",\n  [HierarchicalNavigation=true]\n  ),\n  DeltaTable = DeltaLake.Table(Source),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(DeltaTable, {{\"review_id\", type text}, {\"book_id\", type text}, {\"title\", type text}, {\"author_id\", type text}, {\"name\", type text}, {\"user_id\", type text}, {\"rating\", Int64.Type}, {\"review_text\", type text}, {\"language_code\", type text}, {\"n_votes\", Int64.Type}}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Changed column type\", \"date_added_iso\", each let\r\n    txt    = [date_added],\r\n    parts  = Text.Split(Text.Trim(txt), \" \"),          // [\"Fri\",\"Jul\",\"27\",\"14:06:28\",\"-0700\",\"2012\"]\r\n    monAbbr= try parts{1} otherwise null,\r\n    dayTxt = try parts{2} otherwise null,\r\n    yearTxt= try parts{5} otherwise null,\r\n\r\n    monNum = try Record.Field(\r\n                [Jan=1,Feb=2,Mar=3,Apr=4,May=5,Jun=6,Jul=7,Aug=8,Sep=9,Oct=10,Nov=11,Dec=12],\r\n                monAbbr) otherwise null,\r\n\r\n    iso = if monNum <> null and dayTxt <> null and yearTxt <> null then\r\n            Text.From(Number.FromText(yearTxt)) & \"-\" &\r\n            Text.PadStart(Text.From(monNum), 2, \"0\") & \"-\" &\r\n            Text.PadStart(Text.From(Number.FromText(dayTxt)), 2, \"0\")\r\n          else null\r\nin\r\n    iso), {{\"date_added_iso\", type date}}),\r\n  #\"Removed blank rows\" = Table.SelectRows(#\"Added custom\", each [rating] <> null),\r\n  #\"Removed blank rows 1\" = Table.SelectRows(#\"Removed blank rows\", each [book_id] <> null and [book_id] <> \"\"),\r\n  #\"Removed blank rows 2\" = Table.SelectRows(#\"Removed blank rows 1\",  each [review_text] <> null and [review_text] <> \"\"),\r\n  #\"Added custom 1\" = Table.TransformColumnTypes(Table.AddColumn(#\"Removed blank rows 2\", \"review_length\", each Text.Length(Text.Trim([review_text]))), {{\"review_length\", Int64.Type}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Added custom 1\", each [review_length] >= 10),\r\n  #\"Removed errors\" = Table.RemoveRowsWithErrors(#\"Filtered rows\", {\"date_added_iso\"}),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Removed errors\", each [date_added_iso] < #date(2025, 11, 7)),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Filtered rows 1\", null, 0, Replacer.ReplaceValue, {\"n_votes\"}),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Replaced value\", \"\", \"Unknown\", Replacer.ReplaceValue, {\"language_code\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Replaced value 1\", {{\"title\", each Text.Trim(_), type nullable text}}),\r\n  #\"Trimmed text 1\" = Table.TransformColumns(#\"Trimmed text\", {{\"name\", each Text.Trim(_), type nullable text}}),\r\n  #\"Trimmed text 2\" = Table.TransformColumns(#\"Trimmed text 1\", {{\"review_text\", each Text.Trim(_), type nullable text}}),\r\n  #\"Capitalized each word\" = Table.TransformColumns(#\"Trimmed text 2\", {{\"title\", each Text.Proper(_), type nullable text}}),\r\n  #\"Capitalized each word 1\" = Table.TransformColumns(#\"Capitalized each word\", {{\"name\", each Text.Proper(_), type nullable text}}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Capitalized each word 1\", {\"book_id\"}, avg_rating_bookid, {\"book_id\"}, \"Query (3)\", JoinKind.LeftOuter),\r\n  #\"Grouped rows\" = Table.Group(#\"Merged queries\", {\"author_id\"}, {{\"avg_author_rating\", each List.Average([rating]), type nullable number}})\r\n\r\n\r\n\nin\n  #\"Grouped rows\";\r\nshared word_count_reviews = let\n  Source = AzureStorage.DataLake(\n  \"https://goodreadsreviews60107070.dfs.core.windows.net/lakehouse/gold/curated_reviews/\",\n  [HierarchicalNavigation=true]\n  ),\n  DeltaTable = DeltaLake.Table(Source),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(DeltaTable, {{\"review_id\", type text}, {\"book_id\", type text}, {\"title\", type text}, {\"author_id\", type text}, {\"name\", type text}, {\"user_id\", type text}, {\"rating\", Int64.Type}, {\"review_text\", type text}, {\"language_code\", type text}, {\"n_votes\", Int64.Type}}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Changed column type\", \"date_added_iso\", each let\r\n    txt    = [date_added],\r\n    parts  = Text.Split(Text.Trim(txt), \" \"),          // [\"Fri\",\"Jul\",\"27\",\"14:06:28\",\"-0700\",\"2012\"]\r\n    monAbbr= try parts{1} otherwise null,\r\n    dayTxt = try parts{2} otherwise null,\r\n    yearTxt= try parts{5} otherwise null,\r\n\r\n    monNum = try Record.Field(\r\n                [Jan=1,Feb=2,Mar=3,Apr=4,May=5,Jun=6,Jul=7,Aug=8,Sep=9,Oct=10,Nov=11,Dec=12],\r\n                monAbbr) otherwise null,\r\n\r\n    iso = if monNum <> null and dayTxt <> null and yearTxt <> null then\r\n            Text.From(Number.FromText(yearTxt)) & \"-\" &\r\n            Text.PadStart(Text.From(monNum), 2, \"0\") & \"-\" &\r\n            Text.PadStart(Text.From(Number.FromText(dayTxt)), 2, \"0\")\r\n          else null\r\nin\r\n    iso), {{\"date_added_iso\", type date}}),\r\n  #\"Removed blank rows\" = Table.SelectRows(#\"Added custom\", each [rating] <> null),\r\n  #\"Removed blank rows 1\" = Table.SelectRows(#\"Removed blank rows\", each [book_id] <> null and [book_id] <> \"\"),\r\n  #\"Removed blank rows 2\" = Table.SelectRows(#\"Removed blank rows 1\",  each [review_text] <> null and [review_text] <> \"\"),\r\n  #\"Added custom 1\" = Table.TransformColumnTypes(Table.AddColumn(#\"Removed blank rows 2\", \"review_length\", each Text.Length(Text.Trim([review_text]))), {{\"review_length\", Int64.Type}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Added custom 1\", each [review_length] >= 10),\r\n  #\"Removed errors\" = Table.RemoveRowsWithErrors(#\"Filtered rows\", {\"date_added_iso\"}),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Removed errors\", each [date_added_iso] < #date(2025, 11, 7)),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Filtered rows 1\", null, 0, Replacer.ReplaceValue, {\"n_votes\"}),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Replaced value\", \"\", \"Unknown\", Replacer.ReplaceValue, {\"language_code\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Replaced value 1\", {{\"title\", each Text.Trim(_), type nullable text}}),\r\n  #\"Trimmed text 1\" = Table.TransformColumns(#\"Trimmed text\", {{\"name\", each Text.Trim(_), type nullable text}}),\r\n  #\"Trimmed text 2\" = Table.TransformColumns(#\"Trimmed text 1\", {{\"review_text\", each Text.Trim(_), type nullable text}}),\r\n  #\"Capitalized each word\" = Table.TransformColumns(#\"Trimmed text 2\", {{\"title\", each Text.Proper(_), type nullable text}}),\r\n  #\"Capitalized each word 1\" = Table.TransformColumns(#\"Capitalized each word\", {{\"name\", each Text.Proper(_), type nullable text}}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Capitalized each word 1\", {\"book_id\"}, avg_rating_bookid, {\"book_id\"}, \"Query (3)\", JoinKind.LeftOuter),\r\n  #\"From Value\" = Table.FromValue(#\"Merged queries\"),\r\n  #\"Remove Columns\" = Table.RemoveColumns(#\"From Value\", Table.ColumnsOfType(#\"From Value\", {type table, type record, type list, type nullable binary, type binary, type function}))\r\n\r\n\r\n\nin\n  #\"Remove Columns\";\r\n","connectionOverrides":[{"path":"https://goodreadsreviews60107070.dfs.core.windows.net","kind":"AzureDataLakeStorage","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"AzureDataLakeStorage\",\"path\":\"https://goodreadsreviews60107070.dfs.core.windows.net\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"main","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"main.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"review_id","dataType":"string"},{"name":"book_id","dataType":"string"},{"name":"title","dataType":"string"},{"name":"author_id","dataType":"string"},{"name":"name","dataType":"string"},{"name":"user_id","dataType":"string"},{"name":"rating","dataType":"int64"},{"name":"review_text","dataType":"string"},{"name":"language_code","dataType":"string"},{"name":"n_votes","dataType":"double"},{"name":"date_added","dataType":"string"},{"name":"date_added_iso","dataType":"date"},{"name":"review_length","dataType":"int64"}]},{"$type":"LocalEntity","name":"avg_rating_bookid","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"avg_rating_bookid.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"book_id\"]}]"}],"attributes":[{"name":"book_id","dataType":"string"},{"name":"avg_rating","dataType":"double"}]},{"$type":"LocalEntity","name":"review_count","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"review_count.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"book_id\"]}]"}],"attributes":[{"name":"book_id","dataType":"string"},{"name":"review_count","dataType":"int64"}]},{"$type":"LocalEntity","name":"avg_rating_authorname","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"avg_rating_authorname.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"author_id\"]}]"}],"attributes":[{"name":"author_id","dataType":"string"},{"name":"avg_author_rating","dataType":"double"}]},{"$type":"LocalEntity","name":"word_count_reviews","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"word_count_reviews.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"review_id","dataType":"string"},{"name":"book_id","dataType":"string"},{"name":"title","dataType":"string"},{"name":"author_id","dataType":"string"},{"name":"name","dataType":"string"},{"name":"user_id","dataType":"string"},{"name":"rating","dataType":"int64"},{"name":"review_text","dataType":"string"},{"name":"language_code","dataType":"string"},{"name":"n_votes","dataType":"double"},{"name":"date_added","dataType":"string"},{"name":"date_added_iso","dataType":"date"},{"name":"review_length","dataType":"int64"}]}],"relationships":[{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"avg_rating_bookid","attributeName":"book_id"},"toAttribute":{"entityName":"main","attributeName":"book_id"}},{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"avg_rating_bookid","attributeName":"book_id"},"toAttribute":{"entityName":"word_count_reviews","attributeName":"book_id"}}]}